INSERT INTO riwayat_penyakits (nama)
VALUES
('Hipertensi'),
('Diabetes Melitus'),
('Kolesterol Tinggi/Dislipidemia'),
('Asam Urat'),
('Penyakit Jantung'),
('Penyakit Ginjal'),
('Penyakit Hati'),
('Gastritis/Maag'),
('GERD'),
('Stroke'),
('Gangguan Tiroid'),
('PCOS'),
('Anemia'),
('Asma'),
('Penyakit Paru'),
('Penyakit Tulang dan Sendi'),
('Obesitas'),
('Penyakit Lambung dan Usus'),
('Kanker'),
('Penyakit Autoimun'),
('Kekurang Gizi'),
('Tidak Ada');
