CREATE TABLE IF NOT EXISTS "pasiens" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
	"nama" VARCHAR(100) NOT NULL,
	"alamat" VARCHAR(255),
	"tempat_lahir" VARCHAR(255) NOT NULL,
	"tanggal_lahir" DATE NOT NULL,
	"pekerjaan_id" INTEGER NOT NULL,
	-- (82xxxxxxxxxxx)
	"nomor_hp" VARCHAR(16),
	"email" VARCHAR(100) UNIQUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "pasiens_pekerjaan_fk" FOREIGN KEY ("pekerjaan_id") REFERENCES pekerjaans("internal_id"),
	PRIMARY KEY("internal_id")
);


COMMENT ON COLUMN "pasiens"."nomor_hp" IS '(82xxxxxxxxxxx)';
ALTER TABLE "pasiens"
ADD FOREIGN KEY("pekerjaan_id") REFERENCES "pekerjaans"("internal_id");
CREATE INDEX "pasiens_nama_index"
ON "pasiens" ("nama");
CREATE INDEX "pasiens_public_id_index"
ON "pasiens" ("public_id");
CREATE INDEX "pasiens_pekerjaan_index"
ON "pasiens" ("pekerjaan_id");
