CREATE TABLE IF NOT EXISTS "riwayat_penyakit_pasiens" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
	"pasien_id" INTEGER NOT NULL,
	"riwayat_penyakit_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "riwayat_penyakit_pasien_pasien_fk" FOREIGN KEY ("pasien_id") REFERENCES "pasiens"("internal_id") ON DELETE CASCADE,
  CONSTRAINT "riwayat_penyakit_pasien_riwayat_penyakit_fk" FOREIGN KEY ("riwayat_penyakit_id") REFERENCES "riwayat_penyakits"("internal_id") ON DELETE CASCADE,
  CONSTRAINT "riwayat_penyakit_pasien_unique_constraint" UNIQUE ("pasien_id", "riwayat_penyakit_id"),
  PRIMARY KEY("internal_id")
);
