insert into pekerjaans (nama) values ('Dokter');
insert into pekerjaans (nama) values ('Perawat');
insert into pekerjaans (nama) values ('Guru');
insert into pekerjaans (nama) values ('Dosen');
insert into pekerjaans (nama) values ('Mahasiswa');
insert into pekerjaans (nama) values ('Koki');
insert into pekerjaans (nama) values ('Pengacara');
insert into pekerjaans (nama) values ('Polisi');
insert into pekerjaans (nama) values ('Tentara');
insert into pekerjaans (nama) values ('Tidak Bekerja');
