CREATE TABLE IF NOT EXISTS "pantangans" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"nama" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("internal_id")
);
