CREATE TYPE metode_pembayaran AS ENUM (
  'Cash',
  'Transfer',
  'Qris'
);

CREATE TABLE IF NOT EXISTS "tagihans" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"public_id" UUID UNIQUE DEFAULT gen_random_uuid(),

  "kunjungan_id" INTEGER NOT NULL UNIQUE,

  "biaya_konsultasi" INTEGER NOT NULL,
  "biaya_alat" INTEGER NOT NULL,
  "metode_bayar" metode_pembayaran NOT NULL,

  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "deleted_at" TIMESTAMPTZ,
  CONSTRAINT "tagihan_kunjungan_fk" FOREIGN KEY ("kunjungan_id") REFERENCES "kunjungans"("internal_id")
);
