CREATE TABLE IF NOT EXISTS "data_labs" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"kunjungan_id" INTEGER NOT NULL,
	"parameter_id" INTEGER NOT NULL,
	"nilai" DECIMAL NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "data_lab_kunjungan_fk" FOREIGN KEY ("kunjungan_id") REFERENCES "kunjungans"("internal_id"),
  CONSTRAINT "data_lab_parameter_fk" FOREIGN KEY ("parameter_id") REFERENCES "parameter_pemeriksaan_darahs"("internal_id"),
	PRIMARY KEY("internal_id")
);
