insert into alergis (nama) values ('Alergi Seafood');
insert into alergis (nama) values ('Alergi Coklat');
insert into alergis (nama) values ('Alergi Susu');
insert into alergis (nama) values ('Alergi Telur');
insert into alergis (nama) values ('Alergi Obat');
insert into alergis (nama) values ('Alergi Buah');
insert into alergis (nama) values ('Alergi Kacang');
insert into alergis (nama) values ('Alergi Jamur');
insert into alergis (nama) values ('Alergi Daging Merah');
insert into alergis (nama) values ('Alergi Ikan');
