CREATE TABLE IF NOT EXISTS "alergi_pasiens" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
	"pasien_id" INTEGER NOT NULL,
	"alergi_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "alergi_pasien_pasien_fk" FOREIGN KEY ("pasien_id") REFERENCES "pasiens"("internal_id"),
  CONSTRAINT "alergi_pasien_alergi_fk" FOREIGN KEY ("alergi_id") REFERENCES "alergis"("internal_id"),
  PRIMARY KEY("id")
);
