CREATE TABLE IF NOT EXISTS "pemeriksaans" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID UNIQUE DEFAULT gen_random_uuid(),
	"kunjungan_id" INTEGER NOT NULL UNIQUE,
	"subjective" TEXT NOT NULL,
	"objective" TEXT NOT NULL,
	"planning_terapi" TEXT NOT NULL,
	"evaluasi" TEXT NOT NULL,
	"diperiksa_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "pemeriksaan_kunjungan_fk" FOREIGN KEY ("kunjungan_id") REFERENCES "kunjungans"("internal_id"),
	PRIMARY KEY("internal_id")
);
