CREATE TABLE IF NOT EXISTS "kunjungans" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"pasien_id" INTEGER NOT NULL,
	"tanggal" TIMESTAMPTZ NOT NULL,
	-- (mm/Hg)
	"tensi_sistol" SMALLINT NOT NULL,
	-- (mm/Hg)
	"tensi_diastol" SMALLINT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "kunjungans_pasien_fk" FOREIGN KEY ("pasien_id") REFERENCES "pasiens"("internal_id"),
	PRIMARY KEY("internal_id")
);

COMMENT ON COLUMN "kunjungans"."tensi_sistol" IS '(mm/Hg)';
COMMENT ON COLUMN "kunjungans"."tensi_diastol" IS '(mm/Hg)';
CREATE INDEX "kunjungans_pasien_index"
ON "kunjungans" ("pasien_id");
