CREATE TABLE IF NOT EXISTS "parameter_pemeriksaan_darahs" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"nama" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
	"satuan" VARCHAR(255),
	PRIMARY KEY("internal_id")
);

CREATE INDEX "parameter_pemeriksaan_darahs_nama_index"
ON "parameter_pemeriksaan_darahs" ("nama");
