insert into pantangans (nama) values ('Alkohol');
insert into pantangans (nama) values ('Garam Berlebihan');
insert into pantangans (nama) values ('Gula Berlebihan');
insert into pantangans (nama) values ('Makanan Mentah');
insert into pantangans (nama) values ('Makanan Pengawet');
insert into pantangans (nama) values ('Makanan Gosong');
insert into pantangans (nama) values ('Minuman Bersoda');
insert into pantangans (nama) values ('Junk Food');
insert into pantangans (nama) values ('Penyedap Berlebihan (MSG)');
insert into pantangans (nama) values ('Pemanis Buatan');
