CREATE TABLE IF NOT EXISTS "komposisi_tubuhs" (
	"internal_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"public_id" UUID NOT NULL DEFAULT gen_random_uuid(),
	"kunjungan_id" INTEGER NOT NULL,
	-- (Kg)
	"berat_badan" DECIMAL NOT NULL,
	-- (cm)
	"tinggi_badan" DECIMAL NOT NULL,
	-- (Kg)
	"massa_lemak" DECIMAL NOT NULL,
	-- (Kg)
	"massa_otot" DECIMAL NOT NULL,
	-- (Kg)
	"massa_tulang" DECIMAL NOT NULL,
	-- (L)
	"air_tubuh" DECIMAL NOT NULL,
	-- (Kg/m^2)
	"indeks_massa_tubuh" DECIMAL NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"deleted_at" TIMESTAMPTZ,
  CONSTRAINT "komposisi_tubuh_kunjungan_fk" FOREIGN KEY ("kunjungan_id") REFERENCES "kunjungans"("internal_id"),
	PRIMARY KEY("internal_id")
);

COMMENT ON COLUMN "komposisi_tubuhs"."berat_badan" IS '(Kg)';
COMMENT ON COLUMN "komposisi_tubuhs"."tinggi_badan" IS '(cm)';
COMMENT ON COLUMN "komposisi_tubuhs"."massa_lemak" IS '(Kg)';
COMMENT ON COLUMN "komposisi_tubuhs"."massa_otot" IS '(Kg)';
COMMENT ON COLUMN "komposisi_tubuhs"."massa_tulang" IS '(Kg)';
COMMENT ON COLUMN "komposisi_tubuhs"."air_tubuh" IS '(L)';
COMMENT ON COLUMN "komposisi_tubuhs"."indeks_massa_tubuh" IS '(Kg/m^2)';
