insert into parameter_pemeriksaan_darahs (nama, satuan) values ('GDS/GDP', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('GPT', 'U/L');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('GOT', 'U/L');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('TG', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('LDL', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('HDL', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('Kolesterol Total', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('Ureum', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('Kreatinin', 'mg/dL');
insert into parameter_pemeriksaan_darahs (nama, satuan) values ('HbA1c', '%');
